name: Build on DockerHub and Deploy to AWS

on: workflow_dispatch

jobs:
  build:
    name: Build on DockerHub
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3





    
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest


