name: Build on DockerHub and Deploy to AWS

on: workflow_dispatch

jobs:
  build:
    name: Build on DockerHub
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'temurin'
            cache: maven

        - name: Build with Maven
          run: mvn -B package --file pom.xml
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-rest:latest
            
  deploy:
    needs: build
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
     - name: Set permissions for private key
       run: |
        echo "${{ secrets.AWS_PRIVATE_KEY }}" > ec2deploy.pem
        chmod 600 ec2deploy.pem
        
     - name: Pull Docker image
       run: |
        ssh -o StrictHostKeyChecking=no -i "ec2deploy.pem" ec2-user@ec2-3-250-143-134.eu-west-1.compute.amazonaws.com 'sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/spring-rest:latest'
        
     - name: Run new container
       run: |
        ssh -o StrictHostKeyChecking=no -i "ec2deploy.pem" ec2-user@ec2-3-250-143-134.eu-west-1.compute.amazonaws.com 'sudo docker run -d --name spring-rest -p 8000:8000 ${{secrets.DOCKERHUB_USERNAME}}/spring-rest:latest'


