# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        java_version: [17]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.python-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.python-version }}
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Code coverage with JaCoCo
      id: jacoco_reporter
      uses: PavanMudigonda/jacoco-reporter@v5.0
      with:
        coverage_results_path: 'target/site/jacoco/jacoco.xml'
        coverage_report_name: JaCoCo
        coverage_report_title: Code Coverage
        skip_check_run: false
        minimum_coverage: 80
        fail_below_threshold: true
        publish_only_summary: true